version: "3.9"

services:
  redis:
    image: redis
    command: redis-server >-
      --health-cmd "redis-cli ping"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
    ports:
      - "6379:6379"
